urls = [
    "https://community.d2l.com/brightspace/kb/articles/23677-about-association-analytics",
    "https://community.d2l.com/brightspace/kb/articles/23675-about-banner-grades",
    "https://community.d2l.com/brightspace/kb/articles/23790-set-up-banner-grades",
    "https://community.d2l.com/brightspace/kb/articles/23801-export-grades-to-banner-grades",
    "https://community.d2l.com/brightspace/kb/articles/23798-about-bizlibrary",
    "https://community.d2l.com/brightspace/kb/articles/23674-set-up-bizlibrary",
    "https://community.d2l.com/brightspace/kb/articles/23792-add-bizlibrary-content-to-brightspace",
    "https://community.d2l.com/brightspace/kb/articles/23679-about-brightspace-extended-administration-by-genius",
    "https://community.d2l.com/brightspace/kb/articles/23805-about-brightspace-integrationhub",
    "https://community.d2l.com/brightspace/kb/articles/23804-configuring-lti-at-the-org-level-to-integrate-brightspace-integrationhub",
    "https://community.d2l.com/brightspace/kb/articles/23803-create-an-external-learning-tool-link-to-brightspace-integrationhub",
    "https://community.d2l.com/brightspace/kb/articles/23802-configure-application-availability-for-instructors",
    "https://community.d2l.com/brightspace/kb/articles/23676-about-class-technologies",
    "https://community.d2l.com/brightspace/kb/articles/23680-copyleaks-overview",
    "https://community.d2l.com/brightspace/kb/articles/23682-crosslisting-management-interface",
    "https://community.d2l.com/brightspace/kb/articles/23686-set-up-crosslisting-management-interface",
    "https://community.d2l.com/brightspace/kb/articles/23684-manage-clmi",
    "https://community.d2l.com/brightspace/kb/articles/23678-about-d2l-link",
    "https://community.d2l.com/brightspace/kb/articles/23671-using-the-d2l-link-admin-dashboard",
    "https://community.d2l.com/brightspace/kb/articles/23690-viewing-d2l-link-recipe-job-reports",
    "https://community.d2l.com/brightspace/kb/articles/23688-about-feedbackfruits",
    "https://community.d2l.com/brightspace/kb/articles/23672-go1-digital-training-content",
    "https://community.d2l.com/brightspace/kb/articles/23687-about-google-workspace",
    "https://community.d2l.com/brightspace/kb/articles/23793-manage-google-workspace-accounts",
    "https://community.d2l.com/brightspace/kb/articles/23795-configure-google-workspace-settings",
    "https://community.d2l.com/brightspace/kb/articles/23787-configuring-google-workspace-within-the-google-domain",
    "https://community.d2l.com/brightspace/kb/articles/23788-configure-administrator-permissions",
    "https://community.d2l.com/brightspace/kb/articles/23794-google-workspace-configuration-variables",
    "https://community.d2l.com/brightspace/kb/articles/23791-google-workspace-permissions",
    "https://community.d2l.com/brightspace/kb/articles/23796-add-google-workspace-widgets-to-org-and-course-homepages",
    "https://community.d2l.com/brightspace/kb/articles/23789-google-workspace-account-management-scenarios",
    "https://community.d2l.com/brightspace/kb/articles/23799-google-workspace-usage-scenarios",
    "https://community.d2l.com/brightspace/kb/articles/23797-troubleshooting-the-google-workspace-integration",
    "https://community.d2l.com/brightspace/kb/articles/23800-creating-a-meeting-using-google-meet",
    "https://community.d2l.com/brightspace/kb/articles/23806-set-up-google-lti-integrations",
    "https://community.d2l.com/brightspace/kb/articles/23696-google-assignments-integration",
    "https://community.d2l.com/brightspace/kb/articles/23673-google-analytics-integration",
    "https://community.d2l.com/brightspace/kb/articles/23807-about-the-ipsis-platform",
    "https://community.d2l.com/brightspace/kb/articles/23750-enable-the-ipsis-platform-in-brightspace",
    "https://community.d2l.com/brightspace/kb/articles/23808-about-ipsis-administration-plug-play-ui-in-brightspace",
    "https://community.d2l.com/brightspace/kb/articles/23812-enable-notifications-for-ipsis-batch-jobs",
    "https://community.d2l.com/brightspace/kb/articles/23816-about-sis-course-merge",
    "https://community.d2l.com/brightspace/kb/articles/23815-merging-and-unmerging-courses-using-sis-course-merge",
    "https://community.d2l.com/brightspace/kb/articles/23813-about-ipsis-section-association",
    "https://community.d2l.com/brightspace/kb/articles/23809-manage-sis-sections-and-course-offerings",
    "https://community.d2l.com/brightspace/kb/articles/23810-about-ipsis-integration-1-0-non-plug-play-ui",
    "https://community.d2l.com/brightspace/kb/articles/23699-about-the-audit-log-tab",
    "https://community.d2l.com/brightspace/kb/articles/23694-about-the-configuration-tab",
    "https://community.d2l.com/brightspace/kb/articles/23811-about-the-batches-tab",
    "https://community.d2l.com/brightspace/kb/articles/23822-about-d2l-standard-csv",
    "https://community.d2l.com/brightspace/kb/articles/23817-prepare-csv-files-using-the-d2l-standard-csv-format",
    "https://community.d2l.com/brightspace/kb/articles/23819-file-relationships",
    "https://community.d2l.com/brightspace/kb/articles/23762-use-d2l-standard-csv-with-ipsis",
    "https://community.d2l.com/brightspace/kb/articles/23757-about-d2l-standard-csv-2-0-2-1",
    "https://community.d2l.com/brightspace/kb/articles/23749-get-started-with-d2l-standard-csv",
    "https://community.d2l.com/brightspace/kb/articles/23765-access-the-d2l-standard-csv-dashboard",
    "https://community.d2l.com/brightspace/kb/articles/23814-about-the-log-messages-tab",
    "https://community.d2l.com/brightspace/kb/articles/23821-upload-csv-files-and-run-a-batch",
    "https://community.d2l.com/brightspace/kb/articles/23769-about-d2l-standard-csv-validation-mode",
    "https://community.d2l.com/brightspace/kb/articles/23753-update-your-source-system-configuration-and-users-source-id",
    "https://community.d2l.com/brightspace/kb/articles/23818-troubleshoot-processing-jobs",
    "https://community.d2l.com/brightspace/kb/articles/23760-merge-courses-using-the-ipsis-section-association-interface",
    "https://community.d2l.com/brightspace/kb/articles/23820-d2l-standard-csv-file-formats",
    "https://community.d2l.com/brightspace/kb/articles/23773-d2l-standard-csv-file-relationships",
    "https://community.d2l.com/brightspace/kb/articles/23826-users",
    "https://community.d2l.com/brightspace/kb/articles/23825-users-version-2-1-including-sort-last-name",
    "https://community.d2l.com/brightspace/kb/articles/23824-manager-dashboard-and-learning-groups-attributes",
    "https://community.d2l.com/brightspace/kb/articles/23823-enrollments",
    "https://community.d2l.com/brightspace/kb/articles/23834-ellucian-ilp",
    "https://community.d2l.com/brightspace/kb/articles/23845-manifest",
    "https://community.d2l.com/brightspace/kb/articles/23832-set-up-oneroster-v1-1-integration",
    "https://community.d2l.com/brightspace/kb/articles/23843-about-oneroster-csv",
    "https://community.d2l.com/brightspace/kb/articles/23768-how-ipsis-relates-to-brightspace-organization-structure",
    "https://community.d2l.com/brightspace/kb/articles/23844-csv-file-format",
    "https://community.d2l.com/brightspace/kb/articles/23842-using-oneroster",
    "https://community.d2l.com/brightspace/kb/articles/23839-set-up-oneroster-1-1-rest",
    "https://community.d2l.com/brightspace/kb/articles/23837-oneroster-rest-for-blackbaud",
    "https://community.d2l.com/brightspace/kb/articles/23771-oneroster-rest-for-gg4l-school-passport",
    "https://community.d2l.com/brightspace/kb/articles/23838-oneroster-rest-for-classlink",
    "https://community.d2l.com/brightspace/kb/articles/23841-oneroster-rest-for-infinite-campus",
    "https://community.d2l.com/brightspace/kb/articles/23748-oneroster-rest-for-synergy",
    "https://community.d2l.com/brightspace/kb/articles/23833-about-the-lis-v2-0-adapter",
    "https://community.d2l.com/brightspace/kb/articles/23840-oneroster-rest-for-skyward",
    "https://community.d2l.com/brightspace/kb/articles/23836-using-lis-v2-0-services",
    "https://community.d2l.com/brightspace/kb/articles/23689-the-bulk-data-exchange-management-service-bdes",
    "https://community.d2l.com/brightspace/kb/articles/23685-the-course-offering-management-service-coms",
    "https://community.d2l.com/brightspace/kb/articles/23683-the-course-section-management-service-csms",
    "https://community.d2l.com/brightspace/kb/articles/23695-the-course-template-management-service-ctms",
    "https://community.d2l.com/brightspace/kb/articles/23681-the-group-management-service-gms",
    "https://community.d2l.com/brightspace/kb/articles/23831-the-membership-management-service-mms",
    "https://community.d2l.com/brightspace/kb/articles/23828-the-section-association-management-service-sams",
    "https://community.d2l.com/brightspace/kb/articles/23829-the-person-management-service-pms",
    "https://community.d2l.com/brightspace/kb/articles/23835-using-lis-translators",
    "https://community.d2l.com/brightspace/kb/articles/23827-about-the-itranslateannouncebulkdataexchange-translator",
    "https://community.d2l.com/brightspace/kb/articles/23830-about-the-itranslatesupportedservices-translator",
    "https://community.d2l.com/brightspace/kb/articles/23710-about-the-itranslatecourseoffering-interface",
    "https://community.d2l.com/brightspace/kb/articles/23632-about-the-itranslatereadcourseofferingresponse-interface",
    "https://community.d2l.com/brightspace/kb/articles/23736-about-the-itranslatecoursesection-interface",
    "https://community.d2l.com/brightspace/kb/articles/23703-about-the-itranslatecoursetemplate-interface",
    "https://community.d2l.com/brightspace/kb/articles/23633-about-the-itranslatereadcoursesectionresponse-interface",
    "https://community.d2l.com/brightspace/kb/articles/23732-about-the-itranslatemembership-interface",
    "https://community.d2l.com/brightspace/kb/articles/23740-about-the-itranslatereadcoursetemplateresponse-interface",
    "https://community.d2l.com/brightspace/kb/articles/23735-about-the-itranslatemembershipresponse-interface",
    "https://community.d2l.com/brightspace/kb/articles/23711-about-the-itranslatereadgroupresponse-interface",
    "https://community.d2l.com/brightspace/kb/articles/23635-about-the-itranslatereadresultsrequest-interface",
    "https://community.d2l.com/brightspace/kb/articles/23720-about-the-itranslategroup-interface",
    "https://community.d2l.com/brightspace/kb/articles/23737-about-the-itranslatereadresultidsforlineitemwithlineitemtyperesponse-interface",
    "https://community.d2l.com/brightspace/kb/articles/23634-about-the-itranslategradestolisresults-interface",
    "https://community.d2l.com/brightspace/kb/articles/23637-about-the-itranslatesectionassociation-interface",
    "https://community.d2l.com/brightspace/kb/articles/23636-about-the-itranslatereadresultidsforlineitemwithlineitemtyperequest-interface",
    "https://community.d2l.com/brightspace/kb/articles/23704-about-the-itranslatereadpersonresponse-interface",
    "https://community.d2l.com/brightspace/kb/articles/23739-about-the-itranslategradetypeforreplacelineitemrequest-interface",
    "https://community.d2l.com/brightspace/kb/articles/23638-using-lis-handlers",
    "https://community.d2l.com/brightspace/kb/articles/23741-about-the-itranslatereadsectionassociationresponse-interface",
    "https://community.d2l.com/brightspace/kb/articles/23743-using-lis-resolvers",
    "https://community.d2l.com/brightspace/kb/articles/23724-about-the-itranslateperson-interface",
    "https://community.d2l.com/brightspace/kb/articles/23727-lis-configuration-checklist",
    "https://community.d2l.com/brightspace/kb/articles/23747-configure-lis-endpoints",
    "https://community.d2l.com/brightspace/kb/articles/23744-configure-lis-translators-handlers-and-bulk-integration",
    "https://community.d2l.com/brightspace/kb/articles/23639-configure-org-unit-type-mapping-specific-to-lis",
    "https://community.d2l.com/brightspace/kb/articles/23640-lis-configuration-variables",
    "https://community.d2l.com/brightspace/kb/articles/23641-using-ipsis-handlers",
    "https://community.d2l.com/brightspace/kb/articles/23693-about-the-ibulkannouncefailurerequest-interface",
    "https://community.d2l.com/brightspace/kb/articles/23697-about-the-ibulkcancelrequesthandler",
    "https://community.d2l.com/brightspace/kb/articles/23701-about-the-ibulkfilereadyrequesthandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23700-about-the-ibulkfileretriever-interface",
    "https://community.d2l.com/brightspace/kb/articles/23705-about-the-ibulkrequestdatahandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23707-about-the-ibulksendreporthandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23698-about-the-ideletecourseoffering-interface",
    "https://community.d2l.com/brightspace/kb/articles/23712-about-the-ideletecourseofferinghandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23643-about-the-ireadcourseofferinghandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23644-about-the-ireplacecourseofferinghandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23709-about-the-ideletecoursesectionhandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23645-about-the-ireplacecoursesectionhandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23642-about-the-ireadcoursesectionhandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23715-about-the-ireadcoursetemplatehandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23713-about-the-ideletecoursetemplatehandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23719-about-the-ireplacecoursetemplatehandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23714-about-the-ideletedepartmenthandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23717-about-the-ireadenrollmenthandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23647-about-the-ireplaceenrollmenthandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23723-about-the-ireaddepartmenthandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23716-about-the-ideleteenrollmenthandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23726-about-the-ireadgradeshandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23706-about-the-ideleteotherorgunithandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23728-about-the-ireadsectionassociationhandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23646-about-the-ireplacedepartmenthandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23649-about-the-ireplaceorgunithandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23648-about-the-ireadorgunithandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23702-about-the-ideletesectionassociationhandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23650-about-the-ireadsemesterhandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23708-about-the-ideletesemesterhandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23651-about-the-ireaduserhandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23731-about-the-ireplacesectionassociationhandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23654-ipsis-logic",
    "https://community.d2l.com/brightspace/kb/articles/23652-about-the-ireplaceuserhandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23653-ipsis-and-lis-troubleshooting",
    "https://community.d2l.com/brightspace/kb/articles/23734-about-the-ireplacesemesterhandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23729-overview-of-grades-and-ipsis",
    "https://community.d2l.com/brightspace/kb/articles/23655-ways-to-initiate-grades-export",
    "https://community.d2l.com/brightspace/kb/articles/23718-about-the-ideleteuserhandler-interface",
    "https://community.d2l.com/brightspace/kb/articles/23721-grades-export-permissions-and-configurations",
    "https://community.d2l.com/brightspace/kb/articles/23656-push-to-the-sis",
    "https://community.d2l.com/brightspace/kb/articles/23722-ireadgradeshandler",
    "https://community.d2l.com/brightspace/kb/articles/23657-ipushgradeshandler",
    "https://community.d2l.com/brightspace/kb/articles/23738-itranslategradetypeforreplacelineitemrequest",
    "https://community.d2l.com/brightspace/kb/articles/23742-itranslategradestolisresults",
    "https://community.d2l.com/brightspace/kb/articles/23745-itranslatereadresultidsforlineitemwithlineitemtyperequest",
    "https://community.d2l.com/brightspace/kb/articles/23658-pull-by-the-sis",
    "https://community.d2l.com/brightspace/kb/articles/23733-ireadgradeshandler",
    "https://community.d2l.com/brightspace/kb/articles/23751-itranslatereadresultsrequest",
    "https://community.d2l.com/brightspace/kb/articles/23659-itranslategradestolisresults",
    "https://community.d2l.com/brightspace/kb/articles/23725-configure-grades-export-language-terms",
    "https://community.d2l.com/brightspace/kb/articles/23692-about-integrity-advocate",
    "https://community.d2l.com/brightspace/kb/articles/23754-itranslatereadresultidsforlineitemwithlineitemtyperesponse",
    "https://community.d2l.com/brightspace/kb/articles/23660-lti-advantage-v1-3",
    "https://community.d2l.com/brightspace/kb/articles/23661-lti-advantage-developer-faq",
    "https://community.d2l.com/brightspace/kb/articles/23761-lti-1-3-permissions",
    "https://community.d2l.com/brightspace/kb/articles/23730-about-lti-1-3-launch-and-authentication",
    "https://community.d2l.com/brightspace/kb/articles/23746-add-an-lti-link-to-a-navbar",
    "https://community.d2l.com/brightspace/kb/articles/23662-tool-registration-deployment-and-links",
    "https://community.d2l.com/brightspace/kb/articles/23752-assignments-and-grades-services-extension-with-lti-1-3",
    "https://community.d2l.com/brightspace/kb/articles/23755-deep-linking-extension-with-lti-1-3",
    "https://community.d2l.com/brightspace/kb/articles/23756-names-and-roles-extension-with-lti-1-3",
    "https://community.d2l.com/brightspace/kb/articles/23764-security-settings-for-lti-advantage-1-3",
    "https://community.d2l.com/brightspace/kb/articles/23663-org-units-and-role-mapping",
    "https://community.d2l.com/brightspace/kb/articles/23664-lti-migration",
    "https://community.d2l.com/brightspace/kb/articles/23759-setting-iframe-sizes",
    "https://community.d2l.com/brightspace/kb/articles/23665-zoom-lti-pro",
    "https://community.d2l.com/brightspace/kb/articles/23691-managementor",
    "https://community.d2l.com/brightspace/kb/articles/23763-overview-of-microsoft-office-365",
    "https://community.d2l.com/brightspace/kb/articles/23780-microsoft-office-365-permissions",
    "https://community.d2l.com/brightspace/kb/articles/23783-outbound-traffic",
    "https://community.d2l.com/brightspace/kb/articles/23777-office-365-widget-in-brightspace",
    "https://community.d2l.com/brightspace/kb/articles/23758-about-microsoft-teams-meetings",
    "https://community.d2l.com/brightspace/kb/articles/23770-set-up-the-integration-for-the-microsoft-team-meetings-plugin",
    "https://community.d2l.com/brightspace/kb/articles/23772-create-a-microsoft-teams-meeting",
    "https://community.d2l.com/brightspace/kb/articles/23779-set-up-the-integration-for-the-microsoft-team-meetings-widget",
    "https://community.d2l.com/brightspace/kb/articles/23776-brightspace-course-connector-for-microsoft-teams",
    "https://community.d2l.com/brightspace/kb/articles/23666-set-up-ouriginal-plagiarism-checker",
    "https://community.d2l.com/brightspace/kb/articles/23766-readspeaker-docreader",
    "https://community.d2l.com/brightspace/kb/articles/23784-readspeaker-for-html-content",
    "https://community.d2l.com/brightspace/kb/articles/23782-about-the-respondus-lockdown-browser",
    "https://community.d2l.com/brightspace/kb/articles/23667-setting-up-turnitin",
    "https://community.d2l.com/brightspace/kb/articles/23774-top-hat-classroom",
    "https://community.d2l.com/brightspace/kb/articles/23786-set-your-ims-role-and-org-unit-type-configuration",
    "https://community.d2l.com/brightspace/kb/articles/23767-required-brightspace-permissions",
    "https://community.d2l.com/brightspace/kb/articles/23781-review-the-bongo-lti-tool-provider-settings",
    "https://community.d2l.com/brightspace/kb/articles/23775-create-a-plugin-for-virtual-classroom-or-video-assignments",
    "https://community.d2l.com/brightspace/kb/articles/23785-update-and-test-the-external-learning-tools-links",
    "https://community.d2l.com/brightspace/kb/articles/23778-add-virtual-classroom-or-video-assignments-to-the-navbar",
    "https://community.d2l.com/brightspace/kb/articles/23668-glossary-of-terms",
    "https://community.d2l.com/brightspace/kb/articles/23669-ios-native-application",
    "https://community.d2l.com/brightspace/kb/articles/23670-documentation-changes-for-integrations",
]

import requests
from bs4 import BeautifulSoup
from concurrent.futures import ThreadPoolExecutor

def fetch_and_parse(url):
    try:
        response = requests.get(url)
        response.raise_for_status()

        soup = BeautifulSoup(response.text, 'html.parser')
        target_div = soup.find('div', class_='seoSectionColumn mainColumn')

        if target_div:
            print(f"Content from {url} was scanned.")
            return f"{target_div.get_text(strip=False)}\n\n" + "-"*50 + "\n\n"
        else:
            return f"The div was not found in {url}\n\n"

    except requests.RequestException as e:
        return f"Request failed for {url}: {e}\n\n"

with ThreadPoolExecutor() as executor:
    results = executor.map(fetch_and_parse, urls)

    with open('./community articles/integrations_docs.txt', 'w', encoding='utf-8') as file:
        for result in results:
            file.write(result)
