urls = [
    "https://community.d2l.com/brightspace/kb/articles/5539-navigate-brightspace-and-find-your-course",
    "https://community.d2l.com/brightspace/kb/articles/5454-log-in-to-brightspace",
    "https://community.d2l.com/brightspace/kb/articles/1700-customize-your-course-navbar",
    "https://community.d2l.com/brightspace/kb/articles/17054-activate-your-course",
    "https://community.d2l.com/brightspace/kb/articles/1701-create-a-widget-based-homepage",
    "https://community.d2l.com/brightspace/kb/articles/12467-homepage-widget-expansion-pack",
    "https://community.d2l.com/brightspace/kb/articles/18176-brightspace-virtual-assistant",
    "https://community.d2l.com/brightspace/kb/articles/2767-about-brightspace-editor",
    "https://community.d2l.com/brightspace/kb/articles/1689-content-experiences",
    "https://community.d2l.com/brightspace/kb/articles/1691-about-announcements",
    "https://community.d2l.com/brightspace/kb/articles/1696-about-assignments",
    "https://community.d2l.com/brightspace/kb/articles/1695-about-quizzes",
    "https://community.d2l.com/brightspace/kb/articles/19162-about-awards",
    "https://community.d2l.com/brightspace/kb/articles/5496-about-portfolio",
    "https://community.d2l.com/brightspace/kb/articles/1694-about-question-library",
    "https://community.d2l.com/brightspace/kb/articles/5806-about-rubrics",
    "https://community.d2l.com/brightspace/kb/articles/1692-about-discussions",
    "https://community.d2l.com/brightspace/kb/articles/21900-about-grades",
    "https://community.d2l.com/brightspace/kb/articles/1686-about-classlist",
    "https://community.d2l.com/brightspace/kb/articles/1697-about-class-progress",
    "https://community.d2l.com/brightspace/kb/articles/2720-about-media-library",
    "https://community.d2l.com/brightspace/kb/articles/16511-about-calendar",
    "https://community.d2l.com/brightspace/kb/articles/1717-email-others-using-the-email-tool",
    "https://community.d2l.com/brightspace/kb/articles/1704-review-your-classlist",
    "https://community.d2l.com/brightspace/kb/articles/1690-set-up-the-activity-feed-widget-and-post",
    "https://community.d2l.com/brightspace/kb/articles/1705-create-a-welcome-message-using-the-announcements-widget",
    "https://community.d2l.com/brightspace/kb/articles/19163-post-assignments-using-the-activity-feed-widget",
    "https://community.d2l.com/brightspace/kb/articles/19164-control-commenting-on-activity-feed-posts",
    "https://community.d2l.com/brightspace/kb/articles/1703-create-discussion-forums-and-topics",
    "https://community.d2l.com/brightspace/kb/articles/2717-create-and-manage-awards",
    "https://community.d2l.com/brightspace/kb/articles/16507-manage-locations",
    "https://community.d2l.com/brightspace/kb/articles/5807-create-and-manage-seating-charts",
    "https://community.d2l.com/brightspace/kb/articles/16504-manage-course-events-with-the-calendar-tool",
    "https://community.d2l.com/brightspace/kb/articles/2883-brightspace-parent-guardian-web-application-teacher-tip-sheet",
    "https://community.d2l.com/brightspace/kb/articles/2722-brightspace-parent-guardian-mobile-app-teacher-tip-sheet",
    "https://community.d2l.com/brightspace/kb/articles/23418-about-course-administration",
    "https://community.d2l.com/brightspace/kb/articles/17055-about-import-export-copy-components",
    "https://community.d2l.com/brightspace/kb/articles/17057-import-export-or-copy-course-components",
    "https://community.d2l.com/brightspace/kb/articles/19157-about-sis-course-merge",
    "https://community.d2l.com/brightspace/kb/articles/19158-merging-and-unmerging-courses-using-sis-course-merge",
    "https://community.d2l.com/brightspace/kb/articles/2733-view-your-course-using-a-different-role",
    "https://community.d2l.com/brightspace/kb/articles/2724-about-learning-outcomes",
    "https://community.d2l.com/brightspace/kb/articles/2736-add-or-import-standards",
    "https://community.d2l.com/brightspace/kb/articles/2734-align-learning-outcomes-to-course-content-and-activities",
    "https://community.d2l.com/brightspace/kb/articles/16503-best-practices-for-creating-a-course-homepage",
    "https://community.d2l.com/brightspace/kb/articles/16509-manage-widgets-on-your-homepage",
    "https://community.d2l.com/brightspace/kb/articles/16505-displaying-course-grouping-tabs-in-the-my-courses-widget",
    "https://community.d2l.com/brightspace/kb/articles/16506-change-personal-settings-with-the-my-settings-widget",
    "https://community.d2l.com/brightspace/kb/articles/16512-using-the-my-org-units-widget",
    "https://community.d2l.com/brightspace/kb/articles/16513-using-the-photo-banner-widget",
    "https://community.d2l.com/brightspace/kb/articles/16517-using-the-slim-announcements-widget",
    "https://community.d2l.com/brightspace/kb/articles/16514-using-the-visual-table-of-contents-toc-widget",
    "https://community.d2l.com/brightspace/kb/articles/16515-using-the-welcome-window-widget",
    "https://community.d2l.com/brightspace/kb/articles/12463-automatically-customize-course-content-using-replace-strings",
    "https://community.d2l.com/brightspace/kb/articles/1716-set-up-your-grade-book",
    "https://community.d2l.com/brightspace/kb/articles/22384-create-and-delete-grade-categories-and-items",
    "https://community.d2l.com/brightspace/kb/articles/16516-gradebook-icons-and-notifications",
    "https://community.d2l.com/brightspace/kb/articles/6040-change-content-display-settings",
    "https://community.d2l.com/brightspace/kb/articles/2750-add-and-organize-learning-materials-in-the-classic-content-experience",
    "https://community.d2l.com/brightspace/kb/articles/5356-add-and-organize-learning-materials-in-the-new-content-experience-lessons",
    "https://community.d2l.com/brightspace/kb/articles/2742-associate-course-content-with-standards",
    "https://community.d2l.com/brightspace/kb/articles/2744-set-a-course-timeframe",
    "https://community.d2l.com/brightspace/kb/articles/2757-readspeaker-integrations-for-lessons",
    "https://community.d2l.com/brightspace/kb/articles/2755-improve-navigation-in-multi-page-content-topics",
    "https://community.d2l.com/brightspace/kb/articles/2754-hide-content-topics-modules-and-downloads",
    "https://community.d2l.com/brightspace/kb/articles/23031-what-types-of-files-can-i-use-for-course-content",
    "https://community.d2l.com/brightspace/kb/articles/2879-add-availability-and-due-dates-in-content",
    "https://community.d2l.com/brightspace/kb/articles/2752-add-a-release-condition-to-content",
    "https://community.d2l.com/brightspace/kb/articles/2751-manage-rubrics-through-the-quicklinks-menu",
    "https://community.d2l.com/brightspace/kb/articles/2753-use-html-templates-in-content",
    "https://community.d2l.com/brightspace/kb/articles/2768-add-a-learning-objective-to-a-content-topic",
    "https://community.d2l.com/brightspace/kb/articles/2770-insert-and-edit-images-with-brightspace-editor",
    "https://community.d2l.com/brightspace/kb/articles/2766-create-and-insert-a-video-note-in-brightspace-editor",
    "https://community.d2l.com/brightspace/kb/articles/2769-insert-and-edit-equations-with-equation-editor",
    "https://community.d2l.com/brightspace/kb/articles/2782-about-brightspace-creator",
    "https://community.d2l.com/brightspace/kb/articles/2781-using-the-creator-features-of-brightspace-editor",
    "https://community.d2l.com/brightspace/kb/articles/18177-create-a-presentation-with-capture-web",
    "https://community.d2l.com/brightspace/kb/articles/2780-create-a-presentation-with-the-capture-app",
    "https://community.d2l.com/brightspace/kb/articles/2787-create-and-delete-a-link-or-link-category",
    "https://community.d2l.com/brightspace/kb/articles/2789-fix-broken-links-in-content",
    "https://community.d2l.com/brightspace/kb/articles/2864-add-and-edit-categories-to-manage-assignments",
    "https://community.d2l.com/brightspace/kb/articles/2776-create-an-assignment",
    "https://community.d2l.com/brightspace/kb/articles/2775-copy-an-existing-assignment",
    "https://community.d2l.com/brightspace/kb/articles/2774-copy-assignments-to-other-courses",
    "https://community.d2l.com/brightspace/kb/articles/2871-hide-draft-assignments-and-content",
    "https://community.d2l.com/brightspace/kb/articles/2779-set-release-conditions-and-special-access-in-assignments",
    "https://community.d2l.com/brightspace/kb/articles/2778-reorder-edit-and-delete-assignments-and-categories",
    "https://community.d2l.com/brightspace/kb/articles/2859-align-learning-outcomes-to-assignments",
    "https://community.d2l.com/brightspace/kb/articles/2777-preview-assignments-in-evaluation-mode",
    "https://community.d2l.com/brightspace/kb/articles/2773-about-anonymous-marking",
    "https://community.d2l.com/brightspace/kb/articles/2790-set-availability-and-due-dates-for-an-assignment",
    "https://community.d2l.com/brightspace/kb/articles/2867-restricted-file-extensions",
    "https://community.d2l.com/brightspace/kb/articles/2876-assignments-and-turnitin",
    "https://community.d2l.com/brightspace/kb/articles/2795-create-and-configure-a-quiz",
    "https://community.d2l.com/brightspace/kb/articles/22658-applying-respondus-lockdown-browser-to-a-quiz",
    "https://community.d2l.com/brightspace/kb/articles/19160-manage-quiz-questions",
    "https://community.d2l.com/brightspace/kb/articles/2797-manage-questions-in-the-quiz-builder",
    "https://community.d2l.com/brightspace/kb/articles/19159-quizzes-faq-hot-tips-and-workarounds",
    "https://community.d2l.com/brightspace/kb/articles/2800-creating-question-library-questions",
    "https://community.d2l.com/brightspace/kb/articles/2887-managing-questions-in-question-library",
    "https://community.d2l.com/brightspace/kb/articles/2802-quizzes-and-question-library",
    "https://community.d2l.com/brightspace/kb/articles/2801-delete-and-copy-questions-from-question-library-in-a-quiz",
    "https://community.d2l.com/brightspace/kb/articles/1708-add-existing-activities-with-google-drive",
    "https://community.d2l.com/brightspace/kb/articles/1709-add-existing-activities-with-onedrive",
    "https://community.d2l.com/brightspace/kb/articles/22810-using-virtual-classrooms-and-video-assignments-by-bongo",
    "https://community.d2l.com/brightspace/kb/articles/23554-about-release-conditions",
    "https://community.d2l.com/brightspace/kb/articles/23552-attach-release-conditions",
    "https://community.d2l.com/brightspace/kb/articles/2874-about-game-based-learning-gbl",
    "https://community.d2l.com/brightspace/kb/articles/2866-create-and-manage-game-maps",
    "https://community.d2l.com/brightspace/kb/articles/12466-upload-edit-and-play-audio-video-content-with-media-player",
    "https://community.d2l.com/brightspace/kb/articles/2808-view-and-download-audio-video-transcripts",
    "https://community.d2l.com/brightspace/kb/articles/2809-manage-audio-video-content-with-media-library",
    "https://community.d2l.com/brightspace/kb/articles/5352-import-and-manage-scorm",
    "https://community.d2l.com/brightspace/kb/articles/6039-view-user-progress-in-content",
    "https://community.d2l.com/brightspace/kb/articles/5798-create-a-rubric-using-the-rubrics-tool",
    "https://community.d2l.com/brightspace/kb/articles/19161-evaluate-quizzes",
    "https://community.d2l.com/brightspace/kb/articles/2810-manage-quizzes-with-learner-attempts",
    "https://community.d2l.com/brightspace/kb/articles/2813-view-quiz-statistics-and-attempt-logs",
    "https://community.d2l.com/brightspace/kb/articles/1714-evaluate-with-quick-eval",
    "https://community.d2l.com/brightspace/kb/articles/5498-define-portfolio-class-settings",
    "https://community.d2l.com/brightspace/kb/articles/5519-filter-classlists-by-section",
    "https://community.d2l.com/brightspace/kb/articles/5500-ideas-for-using-brightspace-portfolio-in-k-12-organizations",
    "https://community.d2l.com/brightspace/kb/articles/5508-set-up-the-brightspace-portfolio-app",
    "https://community.d2l.com/brightspace/kb/articles/5509-using-the-brightspace-portfolio-app-in-the-classroom",
    "https://community.d2l.com/brightspace/kb/articles/5510-access-your-classroom-with-your-passcard",
    "https://community.d2l.com/brightspace/kb/articles/5511-collect-evidence-using-the-brightspace-portfolio-app-in-your-classroom",
    "https://community.d2l.com/brightspace/kb/articles/5502-print-passcards-for-your-classroom-and-learners",
    "https://community.d2l.com/brightspace/kb/articles/5505-use-passcards",
    "https://community.d2l.com/brightspace/kb/articles/5501-print-an-individual-passcard-for-a-learner",
    "https://community.d2l.com/brightspace/kb/articles/5503-security-precautions-built-in-to-the-passcard-system",
    "https://community.d2l.com/brightspace/kb/articles/5536-managing-evidence-with-categories",
    "https://community.d2l.com/brightspace/kb/articles/5504-troubleshooting-no-passcards-appear-when-i-click-print-passcards",
    "https://community.d2l.com/brightspace/kb/articles/5512-troubleshooting-qr-codes-in-passcards-do-not-work",
    "https://community.d2l.com/brightspace/kb/articles/5513-troubleshooting-do-you-need-to-scan-a-passcard-every-time-you-use-brightspace-portfolio",
    "https://community.d2l.com/brightspace/kb/articles/1712-brightspace-portfolio-use-passcards-to-collect-evidence",
    "https://community.d2l.com/brightspace/kb/articles/5495-using-the-brightspace-portfolio-app-from-home",
    "https://community.d2l.com/brightspace/kb/articles/5534-download-a-learner-passcard-for-brightspace-portfolio-home-mode",
    "https://community.d2l.com/brightspace/kb/articles/5514-manage-evidence",
    "https://community.d2l.com/brightspace/kb/articles/1711-manage-categories",
    "https://community.d2l.com/brightspace/kb/articles/5517-retire-a-category",
    "https://community.d2l.com/brightspace/kb/articles/5515-add-a-new-category",
    "https://community.d2l.com/brightspace/kb/articles/5518-rename-a-category",
    "https://community.d2l.com/brightspace/kb/articles/5516-approve-evidence-before-adding-it-to-a-portfolio",
    "https://community.d2l.com/brightspace/kb/articles/5521-share-evidence-with-parents-or-guardians",
    "https://community.d2l.com/brightspace/kb/articles/5522-spotlight-evidence",
    "https://community.d2l.com/brightspace/kb/articles/5520-perform-bulk-actions-on-evidence",
    "https://community.d2l.com/brightspace/kb/articles/5535-add-categories-to-evidence",
    "https://community.d2l.com/brightspace/kb/articles/5533-review-and-assess-submitted-portfolio-evidence",
    "https://community.d2l.com/brightspace/kb/articles/5527-archive-evidence",
    "https://community.d2l.com/brightspace/kb/articles/5525-add-private-educator-notes-or-comments-to-evidence",
    "https://community.d2l.com/brightspace/kb/articles/2807-assess-student-work-against-learning-outcomes",
    "https://community.d2l.com/brightspace/kb/articles/2814-assess-learning-outcomes-in-rubric-criteria",
    "https://community.d2l.com/brightspace/kb/articles/2826-manually-map-achievement-levels-to-rubric-levels",
    "https://community.d2l.com/brightspace/kb/articles/2829-reviewing-suggested-achievement-outcomes",
    "https://community.d2l.com/brightspace/kb/articles/2827-reviewing-suggested-achievement-levels",
    "https://community.d2l.com/brightspace/kb/articles/2710-assessing-assignment-submissions",
    "https://community.d2l.com/brightspace/kb/articles/2828-assessing-assignment-submissions-against-standards",
    "https://community.d2l.com/brightspace/kb/articles/2825-assessing-discussion-threads",
    "https://community.d2l.com/brightspace/kb/articles/2824-assessing-discussion-topic-responses-against-a-learning-objective",
    "https://community.d2l.com/brightspace/kb/articles/2869-assess-users-in-discussion-threads",
    "https://community.d2l.com/brightspace/kb/articles/2835-creating-and-editing-competencies-learning-objectives-and-activities",
    "https://community.d2l.com/brightspace/kb/articles/2865-understanding-competency-status-settings",
    "https://community.d2l.com/brightspace/kb/articles/2821-delete-a-competency",
    "https://community.d2l.com/brightspace/kb/articles/2818-create-a-competency",
    "https://community.d2l.com/brightspace/kb/articles/2823-modify-an-approved-competency",
    "https://community.d2l.com/brightspace/kb/articles/2816-copy-a-competency",
    "https://community.d2l.com/brightspace/kb/articles/2817-copy-a-learning-objective",
    "https://community.d2l.com/brightspace/kb/articles/2819-create-a-learning-objective",
    "https://community.d2l.com/brightspace/kb/articles/2822-delete-a-learning-objective",
    "https://community.d2l.com/brightspace/kb/articles/2815-associating-activities",
    "https://community.d2l.com/brightspace/kb/articles/2839-how-an-automatic-evaluation-is-initiated",
    "https://community.d2l.com/brightspace/kb/articles/2830-types-of-activities",
    "https://community.d2l.com/brightspace/kb/articles/2712-allow-automatic-competency-evaluation-after-a-user-achieves-a-competency",
    "https://community.d2l.com/brightspace/kb/articles/2845-turn-off-automatic-competency-evaluation",
    "https://community.d2l.com/brightspace/kb/articles/2840-manually-initiate-an-evaluation",
    "https://community.d2l.com/brightspace/kb/articles/2838-evaluate-survey-activities",
    "https://community.d2l.com/brightspace/kb/articles/2837-evaluate-quiz-activity-manually",
    "https://community.d2l.com/brightspace/kb/articles/2836-evaluate-grade-item-activity-manually",
    "https://community.d2l.com/brightspace/kb/articles/2832-associate-a-learning-objective-with-an-activity",
    "https://community.d2l.com/brightspace/kb/articles/2846-understanding-competency-structures-and-associations",
    "https://community.d2l.com/brightspace/kb/articles/2878-associate-a-competency-structure-element-with-another-existing-element",
    "https://community.d2l.com/brightspace/kb/articles/2834-associate-a-learning-objective-with-a-grade-item",
    "https://community.d2l.com/brightspace/kb/articles/2833-associate-a-learning-objective-with-an-assignment",
    "https://community.d2l.com/brightspace/kb/articles/2842-remove-an-association-between-competency-structure-elements",
    "https://community.d2l.com/brightspace/kb/articles/2843-remove-associations-between-a-learning-objective-and-an-activity-from-another-tool-area",
    "https://community.d2l.com/brightspace/kb/articles/2844-share-a-competency-structure",
    "https://community.d2l.com/brightspace/kb/articles/2847-view-competency-structure-results",
    "https://community.d2l.com/brightspace/kb/articles/2841-override-a-users-result",
    "https://community.d2l.com/brightspace/kb/articles/2831-associate-an-independent-learning-objective-or-activity-to-a-parent-element",
    "https://community.d2l.com/brightspace/kb/articles/2849-assess-brightspace-portfolio-evidence-against-standards",
    "https://community.d2l.com/brightspace/kb/articles/2850-assess-quiz-submissions-against-standards",
    "https://community.d2l.com/brightspace/kb/articles/2848-displaying-rubric-scores-on-the-assess-topic-page",
    "https://community.d2l.com/brightspace/kb/articles/2889-view-course-progress-against-standards",
    "https://community.d2l.com/brightspace/kb/articles/2858-view-assessment-details-on-the-outcomes-progress-details-page",
    "https://community.d2l.com/brightspace/kb/articles/2851-view-student-achievement-for-multiple-quiz-attempts",
    "https://community.d2l.com/brightspace/kb/articles/2857-allow-students-to-reflect-on-their-learning",
    "https://community.d2l.com/brightspace/kb/articles/2856-reasons-to-use-self-assessments",
    "https://community.d2l.com/brightspace/kb/articles/2852-best-practices-for-creating-and-using-self-assessments",
    "https://community.d2l.com/brightspace/kb/articles/2855-evaluating-self-assessments",
    "https://community.d2l.com/brightspace/kb/articles/2853-create-a-self-assessment",
    "https://community.d2l.com/brightspace/kb/articles/2854-delete-a-self-assessment",
    "https://community.d2l.com/brightspace/kb/articles/2862-share-self-assessment-questions-with-other-instructors",
    "https://community.d2l.com/brightspace/kb/articles/1715-manage-final-grades",
    "https://community.d2l.com/brightspace/kb/articles/12464-drop-the-lowest-grade",
    "https://community.d2l.com/brightspace/kb/articles/1687-create-accessible-content-in-brightspace",
    "https://community.d2l.com/brightspace/kb/articles/1685-access-course-content-using-the-readspeaker-docreader-integration",
    "https://community.d2l.com/brightspace/kb/articles/23553-glossary-of-terms",
    "https://community.d2l.com/brightspace/kb/articles/5808-documentation-changes-for-k12-teachers",
]

import requests
from bs4 import BeautifulSoup
from concurrent.futures import ThreadPoolExecutor

def fetch_and_parse(url):
    try:
        response = requests.get(url)
        response.raise_for_status()

        soup = BeautifulSoup(response.text, 'html.parser')
        target_div = soup.find('div', class_='seoSectionColumn mainColumn')

        if target_div:
            print(f"Content from {url} was scanned.")
            return f"{target_div.get_text(strip=False)}\n\n" + "-"*50 + "\n\n"
        else:
            return f"The div was not found in {url}\n\n"

    except requests.RequestException as e:
        return f"Request failed for {url}: {e}\n\n"

with ThreadPoolExecutor() as executor:
    results = executor.map(fetch_and_parse, urls)

    with open('./community articles/k12_instructor.txt', 'w', encoding='utf-8') as file:
        for result in results:
            file.write(result)
